# Header
navbar_brand: linkgo.io
host_home_page: /
menu:
  # Home: index.html
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
#- about         # See also: `about_content`
- category
- tag
- tagcloud
#- archive
- recent_posts
about_widget_content: >
  <p>This blog is <em>made with love</em> by linkgo.io,
    wish these articles make you know us, feel free to contact us.</p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id:
google_plus:
fb_admins:
fb_app_id:
